version: "3.9"

services:
  server:
    build: ./avail_missed_blocks
    container_name: avail_backend
    ports:
      - "8080:8080"
    volumes:
      - ./avail_missed_blocks:/app
      - ./app/node_modules
  db:
    image: "postgres"
    container_name: avail_db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD: "1234"
      - POSTGRES_USER: "postgres"
